" ~/.vimrc

set nocompatible
syntax on
set encoding=utf-8

" ---- Apariencia ----

set number
set cursorline
set showmode
set ruler
set laststatus=2

" ---- Indentacion ----

set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" ---- Busqueda ----

set incsearch
set hlsearch
set ignorecase
set smartcase

" ---- Comportamiento ----

set backspace=indent,eol,start
set wrap
set linebreak
set scrolloff=5
set wildmenu

" ---- Archivos ----

set nobackup
set noswapfile

" ---- Mapeos ----

inoremap jj <Esc>

nnoremap <Esc> :nohlsearch<CR>